updating mbezhanov/faker-provider-collection for using FakerPHP/Faker
bagisto/laravel-data-faker pull request #11
Opened 2021-01-20 19:22 UTC by robinflyhigh

…P/Faker

2021-01-24 07:25 UTC, robinflyhigh commented
@ghermans @jitendra-webkul

2021-01-24 15:49 UTC, ghermans requested changes

2021-01-24 15:49 UTC, ghermans commented on README.md
> +composer require robinflyhigh/bagisto-laravel-data-faker
This should not be changed, please revert this back to `bagisto/laravel-datafaker`.

2021-01-24 15:49 UTC, ghermans commented on composer.json
> +    "name": "robinflyhigh/bagisto-laravel-data-faker",
This should not be changed, please revert this back to
```json
"name": "bagisto/laravel-datafaker",
```

2021-01-27 05:59 UTC, ghermans reviewed
@robinflyhigh please verify the following

2021-02-17 10:10 UTC, palmatesolutions commented
Ignore my pull request. Just update the package.json file

from 
        "mbezhanov/faker-provider-collection": "^1.2"
to
        "mbezhanov/faker-provider-collection": "^2.0"

2021-06-04 01:40 UTC, closed without merging